#!/usr/bin/env python3
"""
Session 6 — turn image files into C arrays for on-device vision.

run_classifier() needs a populated pixel buffer, NOT a .jpg — you can't hand
the chip an image file. So we bake a few pictures into the firmware as arrays.

Usage:
    pip install pillow
    python tools/image_to_header.py person.jpg empty.jpg -o include/test_images.h

Produces, for each input image and each size in SIZES, a grayscale C array:
    const uint8_t person_96[96*96] = { ... };

Feed one to your model at the matching input resolution and time it with millis().
"""
import argparse
import os
from PIL import Image

SIZES = [48, 96, 160]   # the resolutions you'll test the wall at


def to_array(path, size):
    img = Image.open(path).convert("L").resize((size, size))   # grayscale, square
    return list(img.getdata())


def c_name(path, size):
    base = os.path.splitext(os.path.basename(path))[0]
    safe = "".join(c if c.isalnum() else "_" for c in base)
    return f"{safe}_{size}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("images", nargs="+", help="input image files")
    ap.add_argument("-o", "--out", default="include/test_images.h")
    args = ap.parse_args()

    lines = [
        "// Auto-generated by tools/image_to_header.py — do not edit by hand.",
        "// Grayscale test images baked in as C arrays for on-device inference.",
        "#pragma once",
        "#include <stdint.h>",
        "",
    ]
    for path in args.images:
        for size in SIZES:
            data = to_array(path, size)
            name = c_name(path, size)
            body = ", ".join(str(v) for v in data)
            lines.append(f"const uint8_t {name}[{size}*{size}] = {{ {body} }};")
            lines.append("")

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w") as f:
        f.write("\n".join(lines))
    print(f"Wrote {args.out} ({len(args.images)} image(s) x {len(SIZES)} sizes).")


if __name__ == "__main__":
    main()
